### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by vinch** [icure/icure-typescript-sdks#7]
Hello, it's me again.

I'm now giving a try to `@icure/medical-device-sdk` in my favorite JavaScript framework, which is SvelteKit.

My goal is to be able to rebuild something similar to EHR Lite Boilerplate but with SvelteKit (register, login, create patient, etc.)

The thing is, as soon as I import `AnonymousMedTechApi` in my project, I get a 500 error because some dependency tries to access `process` which is a Node-only thing.

![Screenshot 2023-08-11 at 16 37 50](https://github.com/icure/icure-typescript-sdks/assets/155370/44a11fbd-2cef-4104-82f3-8f7625b6818d)

So my question: is this meant to be implemented in the browser or should the package (or at least `AnonymousMedTechApi`) be used only on the server?

Unrelated but while you're at it, could you explain the difference between the EHR Lite SDK and the Medical Device SDK (because they seem very similar to me, from my understanding)?

Thank you!

**Comment by vinch** [comment]
Quick note after testing more thoroughly: it's not only when importing `AnonymousMedTechApi` that I have the problem, it's when I import anything from `@icure/medical-device-sdk`.

**Comment by LotuxPunk** [comment]
Hey @vinch !

Indeed, there's a problem, the intended implementation should work on browser and node environment. We'll work on a patch as soon as possible.

**Comment by vinch** [comment]
Thank you.

To reproduce the problem, you just have to do:

```
$ npm create svelte@latest my-app
$ cd my-app
$ npm install
```
Then add the `@icure/medical-device-sdk` dependency and replace the content of `src/routes/+page.svelte` by:

```
<script lang="ts">
	import { AnonymousMedTechApi } from '@icure/medical-device-sdk';
</script>

<h1>Test</h1>
```

And finally:

```
$ npm run dev -- --open
```

**Comment by trema96** [comment]
> Unrelated but while you're at it, could you explain the difference between the EHR Lite SDK and the Medical Device SDK (because they seem very similar to me, from my understanding)?

Hi @vinch,

As you said at the moment the Medical Device and EHR Lite SDK are very similar. The main difference currently is just the data model (you may have noticed that the terminology used in the EHR Lite is closer to the terminology of FHIR), but in future they may become more diversified.

Our vision is that if you want to build small mobile applications ([like the Petra app we build in the tutorial](https://docs.icure.com/sdks/tutorial/petra/foreword)) or connected medical devices then the Medical Device SDK will better fit your needs. If instead you want to build applications for hospitals the EHR Lite SDK would be a better choice.

**Comment by vinch** [comment]
> Our vision is that if you want to build small mobile applications ([like the Petra app we build in the tutorial](https://docs.icure.com/sdks/tutorial/petra/foreword)) or connected medical devices then the Medical Device SDK will better fit your needs. If instead you want to build applications for hospitals the EHR Lite SDK would be a better choice.

If the idea is to build an EHR application, something similar to Medispring but for the web, what would be the best choice?

**Comment by LotuxPunk** [comment]
Hey @vinch !

We just release new patches on medtech and ehr-lite sdks to fix the behavior you encoutered
- https://www.npmjs.com/package/@icure/ehr-lite-sdk/v/1.0.2
- https://www.npmjs.com/package/@icure/medical-device-sdk/v/3.0.3

Have a great evening !

**Comment by vinch** [comment]
Legendary! Thanks for doing that on a Friday evening!
