### ISSUE TITLE
api.initUserCrypto is not a function

### ISSUE THREAD

**Issue by vinch** [icure/icure-typescript-sdks#9]
Hello, it's me again!

I went through this tutorial (https://docs.icure.com/sdks/tutorial/) but got blocked when trying to init the crypto keys and create the patient.

When I tried to create the patient with `api.patientApi.createOrModifyPatient(patient)`, I got the following error which is fine because I probably need to get my keys first (the 409 error is still strange though):

![Screenshot 2023-08-21 at 12 17 16](https://github.com/icure/icure-typescript-sdks/assets/155370/e7399c4d-a55a-4274-844f-573cedcd8140)

So I tried to create the keys with `api.initUserCrypto` but this is the error I got:

![Screenshot 2023-08-21 at 12 17 34](https://github.com/icure/icure-typescript-sdks/assets/155370/792bc537-21da-4e73-8b19-931ba3a2c380)

**Any idea what I'm doing wrong?**

The complete code of my mini test app (Svelte):

```
<script lang="ts">
	import { AnonymousMedTechApi, SimpleCryptoStrategies, Patient } from '@icure/medical-device-sdk';
	import FriendlyCaptcha from '$lib/components/FriendlyCaptcha.svelte';
	import storage from '$lib/utils/storage';
	import {
		PUBLIC_EXTERNAL_SERVICES_SPEC_ID,
		PUBLIC_EMAIL_AUTHENTICATION_PROCESS_ID,
		PUBLIC_APP_PARENT_ORGANISATION_ID
	} from '$env/static/public';

	let email: string = '';
	let validationCode: string = '';

	let captchaSolution: string;
	let anonymousApi: any;
	let authProcess: any;
	let waitingForToken: boolean = false;
	let api: any;
	let user: any;

	const handleCaptchaSuccess = (solution: string) => {
		captchaSolution = solution;
	};

	const startAuthentication = async () => {
		anonymousApi = await new AnonymousMedTechApi.Builder()
			.withICureBaseUrl('https://krakenc.icure.cloud')
			.withCrypto(crypto)
			.withMsgGwSpecId(PUBLIC_EXTERNAL_SERVICES_SPEC_ID)
			.withAuthProcessByEmailId(PUBLIC_EMAIL_AUTHENTICATION_PROCESS_ID)
			.withStorage(storage)
			.withCryptoStrategies(new SimpleCryptoStrategies([]))
			.build();

		authProcess = await anonymousApi.authenticationApi.startAuthentication(
			captchaSolution,
			email,
			undefined,
			'Vincent',
			'Battaglia',
			PUBLIC_APP_PARENT_ORGANISATION_ID,
			undefined,
			6,
			'friendly-captcha'
		);

		console.log(authProcess);

		waitingForToken = true;
	};

	const completeAuthentication = async () => {
		const result = await anonymousApi.authenticationApi.completeAuthentication(
			authProcess,
			validationCode
		);
		api = result.api;

		console.log(api);

		user = await api.userApi.getLogged();

		console.log(user);
	};

	const handleSubmit = (e: any) => {
		if (waitingForToken) {
			completeAuthentication();
		} else {
			startAuthentication();
		}
	};

	const initUserCrypto = async () => {
		const result = await api.initUserCrypto();

		console.log(result);
	};

	const createPatient = async () => {
		const patient = new Patient({
			firstName: 'John',
			lastName: 'Snow'
		});
		const createdPatient = await api.patientApi.createOrModifyPatient(patient);

		console.log(createdPatient);
	};
</script>

<h1>Riva</h1>

<form on:submit={handleSubmit}>
	{#if user}
		<button on:click={initUserCrypto}>Init user crypto</button>
		<button on:click={createPatient}>Create patient</button>
	{:else if captchaSolution}
		<input type="text" name="email" bind:value={email} />
		{#if waitingForToken}
			<input type="text" name="validationCode" bind:value={validationCode} />
		{/if}
		<button type="submit">Submit</button>
	{:else}
		<FriendlyCaptcha onSuccess={handleCaptchaSuccess} />
	{/if}
</form>
```

**Comment by LotuxPunk** [comment]
Hello @vinch !

I will investigate on my end to see if I can reproduce the problem. However, can you confirm that you are indeed using a unique email address for this new patient?

**Comment by vinch** [comment]
> Hello @vinch !
> 
> I will investigate on my end to see if I can reproduce the problem. However, can you confirm that you are indeed using a unique email address for this new patient?

As you can see in the code above, I only create a patient with a `firstName` and a `lastName`. When I add `email`, I have the following error in my text editor: 

```
Argument of type '{ firstName: string; lastName: string; email: string; }' is not assignable to parameter of type 'IPatient'.
  Object literal may only specify known properties, and 'email' does not exist in type 'IPatient'.
```

**Comment by vinch** [comment]
NB: I was able to get rid of the 409 errors by extracting the two buttons "Init user crypto" and "Create patient" from the form. That was my mistake, and it create errors as it was resubmitting the main login form when it should not have.

```
{#if user}
	<button on:click={initUserCrypto}>Init user crypto</button>
	<button on:click={createPatient}>Create patient</button>
{:else if captchaSolution}
	<form on:submit={handleSubmit}>
		<input type="text" name="email" bind:value={email} />
		{#if waitingForToken}
			<input type="text" name="validationCode" bind:value={validationCode} />
		{/if}
		<button type="submit">Submit</button>
	</form>
{:else}
	<FriendlyCaptcha onSuccess={handleCaptchaSuccess} />
{/if}
```

**Comment by LotuxPunk** [comment]
> > Hello @vinch !
> > I will investigate on my end to see if I can reproduce the problem. However, can you confirm that you are indeed using a unique email address for this new patient?
> 
> As you can see in the code above, I only create a patient with a `firstName` and a `lastName`. When I add `email`, I have the following error in my text editor:
> 
> ```
> Argument of type '{ firstName: string; lastName: string; email: string; }' is not assignable to parameter of type 'IPatient'.
>   Object literal may only specify known properties, and 'email' does not exist in type 'IPatient'.
> ```

Sorry, I read too quickly. I thought you were registering a patient through the process and not via the adoc method. So, please ignore my previous comment. :pray:

The error you're encountering doesn't seem to come from createOrModifyPatient but from your user creation process, in my opinion.

Note that you don't need to initialize the crypto yourself anymore; it's now automatically done by the SDK.

**Comment by LotuxPunk** [comment]
> NB: I was able to get rid of the 409 errors by extracting the two buttons "Init user crypto" and "Create patient" from the form. That was my mistake, and it create errors as it was resubmitting the main login form when it should not have.
> 
> ```
> {#if user}
> 	<button on:click={initUserCrypto}>Init user crypto</button>
> 	<button on:click={createPatient}>Create patient</button>
> {:else if captchaSolution}
> 	<form on:submit={handleSubmit}>
> 		<input type="text" name="email" bind:value={email} />
> 		{#if waitingForToken}
> 			<input type="text" name="validationCode" bind:value={validationCode} />
> 		{/if}
> 		<button type="submit">Submit</button>
> 	</form>
> {:else}
> 	<FriendlyCaptcha onSuccess={handleCaptchaSuccess} />
> {/if}
> ```

Alright, that aligns with what I mentioned earlier; it came from the authentication (user creation) process.

Is it resolved? Or do you still have an error related to this topic?

**Comment by vinch** [comment]
@LotuxPunk No, it's not resolved. I was just able to get rid of the 409 errors, but I still have the other errors.

![Screenshot 2023-08-21 at 13 56 09](https://github.com/icure/icure-typescript-sdks/assets/155370/6f43f1f6-8188-42ff-8da5-68ac9ed024d4)

The first two errors are when I click on "Create patient" and the third one is when I click on "Init user crypto".

What do you mean when you say it's related to the user creation? What I did is just copy what you do in the React boilerplate (just translating it from React to Svelte). But what I notice is that the user associated with my email address is considered a patient in the database. Shouldn't it be considered as an HCP?

**Comment by LotuxPunk** [comment]
The problem you have is due to the loading of encryption keys during your user's login.

You should try logging in again with this user after clearing your browser's session. This will ensure that the SDK checks for keys in your `storage` (which you defined in the builder). If no key is found for your user, the SDK will create new ones.

> What do you mean when you say it's related to the user creation? What I did is just copy what you do in the React boilerplate (just translating it from React to Svelte). But what I notice is that the user associated with my email address is considered a patient in the database. Shouldn't it be considered as an HCP?

What I meant was precisely that it was an issue where you called the login process more than once (as you told me earlier).

It's likely that you created a Patient user and not an HCP. To do this, you need to create a process in the Cockpit that allows you to create an HCP and pass it as a parameter in the builder, just as you did with `PUBLIC_EMAIL_AUTHENTICATION_PROCESS_ID`.

**Comment by vinch** [comment]
Thank you! I'll try a few things and let you know.

**Comment by vinch** [comment]
OK OK when registering a practitioner and creating a patient with that user, it works without changing anything to my code. I think we can close this one. Thanks for your help!

**Comment by LotuxPunk** [comment]
Greta ! You're welcome ! 👍
